### PR TITLE
add Docker-Compose for easy editing flow

### PR DESCRIPTION
**Pull request by adaliszk**
- Moved the source files into `./public`
- Changed the theme for a fixed version of the Just the Docs theme
- Added Docker-Compose
- Updated the README with instructions

### CODE REVIEW

**Comment by adaliszk** [comment]
Hey @mad-hammer, @pota0t, @Sam-M-Hall,
let me know if there is an issue with the PR, I want to open another one afterwards adding info on how to set up a server with manual steamcmd and docker. The update itself does not touches the current way of manually running Ruby and Jekyll, though if you guys don't want to worry about ruby and other details then docker-compose is very very simple 😉

**Comment by mad-hammer** [comment]
Hey @adaliszk, that's awesome that you've submitted the very first pull request on this repo :D
I'll be able to have a look at this in an hour or so once I'm finished work 👍 
Just to let you know though, on your point about opening another request to add server set up info, the current focus is on install guides for steam and steamcmd on Win/Linux. As other install methods (wgsm,lgsm,docker etc.) would likely have their own configuration differences that may be inconsistent with the content in 'General Guides', we're not putting detailed install guides up for those at this time. Instead we're thinking an 'Other install methods' page will be added to the install guides, and on that page, we'll link out to all the other good install resources that a user might appreciate 👍

**Review by mad-hammer — APPROVED** [review]

**Comment by mad-hammer** [comment]
@adaliszk I tried merging this in, but then the readme content became the homepage, and other pages had /public/ added to their url. Any advice/thoughts?

**Comment by adaliszk** [comment]
> the current focus is on install guides for steam and steamcmd on Win/Linux. As other install methods (wgsm,lgsm,docker etc.) would likely have their own configuration differences that may be inconsistent with the content in 'General Guides', we're not putting detailed install guides up for those at this time.

That is totally fine, that's actually a really good idea, that way I could write my own guide on my own side and just submit a link to you!

**Comment by adaliszk** [comment]
> @adaliszk I tried merging this in, but then the readme content became the homepage, and other pages had /public/ added to their url. Any advice/thoughts?

That's weird. The `source: "./public"` in the config should just serve the files from that location, I'll do a test on my side to double check and open this again with the findings!

**Pull request merged**
